### ISSUE TITLE
Implement `_silkscreenpins` modifier for `dip` components

### ISSUE THREAD

**Issue by seveibar** [tscircuit/footprinter#33]
When this modifier is added, silkscreen text is draw adjacent to each pin

The text should read `"{pin1}"`, `"{pin2}"` etc.

**Comment by anas-sarkez** [comment]
> [@anas-sarkez](https://github.com/anas-sarkez) i think you did this one? ok to close?

yes

**Comment by anas-sarkez** [comment]
@seveibar 
does we need same this for all footprints?
