### ISSUE TITLE
MS-012 and MS-013 support (common SSOP variants)

### ISSUE THREAD

**Issue by seveibar** [tscircuit/footprinter#6]
![image](https://github.com/tscircuit/footprinter/assets/1910070/ccb31e08-e3dd-4b68-878d-3b8d19bf81f7)

- [ ] Find PDFs for the components shown in the screenshot above with dimensions
- [ ] Introduce new footprint function `ms012`
- [ ] Introduce new footprint function `ms013`

**Comment by ShiboSoftwareDev** [comment]
Will start working on this one, looks like they are just ssop with fixed dimensions

**Comment by ShiboSoftwareDev** [comment]
fixed in #19
