### ISSUE TITLE
stamp footprints (stampboard and stampreceiver)

### ISSUE THREAD

**Issue by seveibar** [tscircuit/footprinter#64]
This is an example stamp footprint. This one has holes but they don't always have holes

Here's an example:
`stampboard43_left20_right20_bottom3_w10mm_p2.54mm_pl1mm_ph_0.5mm_innerhole`

![Image](https://github.com/user-attachments/assets/91a6d513-bdb4-4d88-a933-46af456305bc)

**Comment by seveibar** [comment]
From the pico 2 datasheet

![Image](https://github.com/user-attachments/assets/fc715bab-4fdd-4b12-b823-a407d958bc25)

**Comment by seveibar** [comment]
note that the mounting holes (the large holes) are not part of the stamp

**Comment by seveibar** [comment]
There is another type (it is different) for "receiving stamps", the "stamp" should be used when creating a stamp board like the pico 2, but if you're trying to place a stamp board onto your board you'll need a "stampreceiver" which looks like this

![Image](https://github.com/user-attachments/assets/80531b7e-466c-4c66-880d-a16b7ae93717)

**Comment by seveibar** [comment]
CC @anas-sarkez this is a pretty good one to get started, we'll use this for placing and creating module boards

**Comment by anas-sarkez** [comment]
#68 
@seveibar should this pull request fixed this issue ? or we need to add anything more

**Comment by seveibar** [comment]
@anas-sarkez mostly! We still need to implement `stampreceiver` which is a PCB where you put on the `stampboard`. It's a bit confusing but a keyboard will use a stampreceiver, and somebody designing a module would use the `stampboard`. They're slightly different footprints.
