### ISSUE TITLE
sot23-5 needed for logic gates

### ISSUE THREAD

**Issue by ShiboSoftwareDev** [tscircuit/footprinter#74]
OR gate:
![Image](https://github.com/user-attachments/assets/db159281-81eb-4a96-8d0b-712deae82d5d)

AND gate:
![Image](https://github.com/user-attachments/assets/ba89c484-1553-4036-b557-79954323d99c)

**Comment by seveibar** [comment]
great issue!

**Comment by anas-sarkez** [comment]
#78
