### ISSUE TITLE
Any footprint should have a default number of pins; I shouldn't have to type 'tssop8' to get a footprint just 'tssop'

### ISSUE THREAD

**Issue by ShiboSoftwareDev** [tscircuit/footprinter#75]
- footprints with a set number of pins like sot235 should not have a num_pins param as it is not configurable, while footprints like soic should have num_pins as optional with a default number of pins.

- I want to be able to type stampboard/stampreceiver and see a default footprint without having to specify the number of pins

![Image](https://github.com/user-attachments/assets/efae081a-3eef-435c-b32a-249b6a6f7d7c)

![Image](https://github.com/user-attachments/assets/90bcba27-90ff-448b-9236-f65a979e56d4)

**Comment by ShiboSoftwareDev** [comment]
@anas-sarkez 👀

**Comment by anas-sarkez** [comment]
I agree with you some of footprints are have a constant number of pins which should not be configurable
that's is what I did with sot23-5 (sot235) which you can not pass how many pins you want
![Image](https://github.com/user-attachments/assets/0e6b0911-bea9-4882-8c01-ade29c169f4b)

**Comment by ShiboSoftwareDev** [comment]
yes @anas-sarkez this is how it looks:
![Image](https://github.com/user-attachments/assets/d54a51d8-d676-49a2-90fa-67a9a1149a29)

**Comment by seveibar** [comment]
Instead of having num_pins not exist as a parameter we could also use z.literal(5) etc. that way every footprint at least emits the number of pads

**Comment by ShiboSoftwareDev** [comment]
@seveibar using the .json() method how can I differentiate between num_pins whether it's a literal type or not?

**Comment by anas-sarkez** [comment]
![image](https://github.com/user-attachments/assets/77f43b59-c0ef-47ee-992d-1389e96b91ca)
I think here where .json() gets the params

**Comment by ShiboSoftwareDev** [comment]
@seveibar oh I didn't understand that code until now, thanks. I really should put some time into reading the codebase and understanding it sometimes
