### ISSUE TITLE
sot23-5 is not being created

### ISSUE THREAD

**Issue by ShiboSoftwareDev** [tscircuit/footprinter#84]
![Image](https://github.com/user-attachments/assets/e2738622-b150-46fb-a516-8c6c574f09ed)

**Comment by ShiboSoftwareDev** [comment]
@anas-sarkez

**Comment by anas-sarkez** [comment]
@ShiboSoftwareDev everything is looks good in footprinter repo, May be you need to update the dependency 
![Image](https://github.com/user-attachments/assets/e7d2f305-8469-488e-ac72-50890521ef55)

**Comment by anas-sarkez** [comment]
@ShiboSoftwareDev  you need to update [core](https://github.com/tscircuit/core) repo
