### ISSUE TITLE
New footprint type: "breakoutheaders"

### ISSUE THREAD

**Issue by seveibar** [tscircuit/footprinter#97]
These are two columns of headers

**Comment by AnasSarkiz** [comment]
/attempt #97
@seveibar 
can you provide more details or a data sheet?

**Comment by AnasSarkiz** [comment]
@seveibar 

<img width="518" alt="Image" src="https://github.com/user-attachments/assets/0b3807ee-a7e3-4605-b212-1eb757ae9d26" />

**Comment by seveibar** [comment]
@AnasSarkiz we want something to help @Abse2001 /others with breakout boards for e.g. arduino nano

He currently has to use two headers to make it work, see this board: https://tscircuit.com/Abse2001/Robotic-Arm-Controller

**Comment by AnasSarkiz** [comment]
@seveibar Do we need a 3D component for this?
